# Archivo de Configuración de Catástrofes del Parque
Escape\ de\ dinosaurio\ (posible\ ataque\ a\ turista)=MÁXIMO - CÓDIGO ROJO
Apagón\ Masivo\ (sistemas\ de\ seguridad\ caídos)=CRÍTICO - CÓDIGO NEGRO
Tormenta\ torrencial\ con\ inundaciones=ALTO - CÓDIGO AMARILLO
Falla\ en\ los\ laboratorios\ genéticos=MEDIO - CÓDIGO NARANJA